# Use the official OpenJDK 17 image as a base image
FROM openjdk:17-jdk-slim

# Install Maven
RUN apt-get update && \
    apt-get install -y maven

# Set the working directory in the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Make sure the Maven Wrapper script is executable
RUN chmod +x ./mvnw

# Run the tests using Maven
CMD ["./mvnw", "test"]
