version: '3.8'
services:
  mongo-service:
    image: mongo:latest
    container_name: mongodb-service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  patientms-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patientms-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-service:27017/patientmsdb

  patientms-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: patientms-tests
    depends_on:
      - mongo-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-service:27017/patientmsdb
    entrypoint: ["./mvnw", "test"]

volumes:
  mongo-data:
